# Create a GitHub action to email a report from a file at 6 a.m. daily
name: Email Report

on:
  schedule:
    - cron: "0 6 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Email Report
        uses: dawsonbooth/send-email-action@v1
        with:
          to: "